# Use a Python image with uv pre-installed
FROM ghcr.io/astral-sh/uv:python3.14-bookworm-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    ca-certificates \
    git \
    unzip \
    sudo \
    vim \
    procps \
    jq yq \
    tree \
    ripgrep fd-find  \
    wget tar jq ripgrep openssh-client \
    build-essential sqlite3 && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Setup a non-root user

# Copy the script into the image
COPY ./scripts/init-user.sh /tmp/init-user.sh

# Run the script and then remove it to keep the layer clean
RUN chmod +x /tmp/init-user.sh && \
    /tmp/init-user.sh && \
    rm /tmp/init-user.sh

#uv specific vars
ENV UV_COMPILE_BYTECODE=1 \
    UV_PROJECT_ENVIRONMENT=/home/dev/app/src/.venv \
    VIRTUAL_ENV=/home/dev/app/src/.venv \
    UV_ENV_FILE=.env \
    UV_LINK_MODE=copy \
    UV_TOOL_BIN_DIR=/usr/local/bin

ENV HOME=/home/dev \
    BUN_INSTALL=/home/dev/.bun

SHELL ["/bin/bash", "-c"]
USER dev

RUN curl -fsSL https://bun.sh/install | bash

ENV PATH=/home/dev/.bun/bin:/home/dev/.local/bin:$PATH
# Install the project into `/app`


ENV OPENCODE_SUBAGENT_COMM=ipc
RUN curl -fsSL https://opencode.ai/install | bash


COPY --chown=dev:dev ./dev/mcp-server/ /home/dev/app/

WORKDIR /home/dev/app/

RUN cd src && uv sync && source .venv/bin/activate

# Place executables in the environment at the front of the path
ENV PATH="/home/dev/app/.venv/bin:$PATH"

# Now you can use them immediately



CMD ["sleep", "infinity"]

