services:

  mcp-server:
    container_name: mcp-server
    image: mcp-server:uv-latest
    # build:
    #   context: ../../
    #   dockerfile: ./dev/mcp-server/Dockerfile

    env_file:
      - ./.env
    user: "1000:1000"
    volumes:
      - mcp-server:/home/dev

    labels:
      - "traefik.enable=true"
      # Dynamic Host: memory.mcp.localhost
      #- "traefik.http.routers.memory.rule=Host(`memory.${INTERNAL_DOCKER_HOST}`)"
      - "traefik.http.routers.mcp-server.rule=Host(`mcp-server.local.net`)"
      - "traefik.http.routers.mcp-server.entrypoints=websecure"
      - "traefik.http.routers.mcp-server.tls=true"
      - "traefik.http.services.mcp-server.loadbalancer.server.port=6274"
      
      # FIXED: Force Traefik to use the proxy network to reach this container
      - "traefik.docker.network=internal.net"


    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    networks:
     # - mcp-net
      - internal-net
    restart: unless-stopped
    
volumes:
  mcp-server:
    name: mcp-server

networks:
  internal-net:
    name: internal-net
    external: true
