#!/usr/bin/env bash
# bootstrap_project.sh — Create agentic Docker infrastructure for a project
#
# Usage: ./bootstrap_project.sh <project_name> [agent_count]
#
# Creates:
#   - {project_name}_project_vol (external named volume — shared RO project files)
#   - {project_name}_agent_vol  (external named volume — per-agent RW subpaths)
#   - Subdirectories inside agent_vol for orchestrator + N agents
#   - docker-compose.yml with correct volume/subpath configuration
#
# Requirements: docker

set -euo pipefail

PROJECT_NAME="${1:?Usage: $0 <project_name> [agent_count]}"
AGENT_COUNT="${2:-2}"  # default: orchestrator + 2 agents

PROJECT_VOL="${PROJECT_NAME}_project_vol"
AGENT_VOL="${PROJECT_NAME}_agent_vol"
COMPOSE_FILE="docker-compose.${PROJECT_NAME}.yml"

echo "=== Bootstrapping agentic stack for project: ${PROJECT_NAME} ==="

# ── 1. Create external volumes ──────────────────────────────────────────────

echo "[1/4] Creating external named volumes..."
for vol in "${PROJECT_VOL}" "${AGENT_VOL}"; do
    if docker volume ls --format '{{.Name}}' | grep -qx "${vol}"; then
        echo "  Volume '${vol}' already exists — skipping."
    else
        docker volume create "${vol}"
        echo "  Volume '${vol}' created."
    fi
done

# ── 2. Pre-create subdirectories in agent_vol ───────────────────────────────

echo "[2/4] Pre-creating subdirectories in ${AGENT_VOL}..."
SUBDIRS="orchestrator"
for i in $(seq 1 "${AGENT_COUNT}"); do
    SUBDIRS="${SUBDIRS} agent${i}"
done

# Build mkdir commands for the init container
MKDIR_CMDS=""
for dir in ${SUBDIRS}; do
    MKDIR_CMDS="${MKDIR_CMDS}mkdir -p /vol/${dir} && "
done
MKDIR_CMDS="${MKDIR_CMDS}echo 'Subdirectories created.'"

docker run --rm \
    -v "${AGENT_VOL}:/vol" \
    alpine:latest \
    sh -c "${MKDIR_CMDS}"

echo "  Created: $(echo ${SUBDIRS} | tr ' ' ', ')"

# ── 3. Seed project volume with skeleton (optional) ─────────────────────────

echo "[3/4] Seeding project volume skeleton..."
docker run --rm \
    -v "${PROJECT_VOL}:/vol" \
    alpine:latest \
    sh -c '
        mkdir -p /vol/shared/skills
        mkdir -p /vol/shared/knowledge
        mkdir -p /vol/shared/config
        echo "# Project: ${PROJECT_NAME}" > /vol/README.md
        echo "Skeleton created."
    '

# ── 4. Generate docker-compose.yml ──────────────────────────────────────────

echo "[4/4] Generating ${COMPOSE_FILE}..."

# Build the agent services block
AGENT_SERVICES=""
for i in $(seq 1 "${AGENT_COUNT}"); do
    AGENT_SERVICES+=$(cat <<AGENT_BLOCK

  agent${i}:
    image: langgraph-agent-base:latest
    container_name: ${PROJECT_NAME}_agent${i}
    volumes:
      - type: volume
        source: ${PROJECT_VOL}
        target: /app/project
        read_only: true
      - type: volume
        source: ${AGENT_VOL}
        target: /workspace
        volume:
          subpath: agent${i}
    networks:
      - agent_net
AGENT_BLOCK
)
done

# Write full compose file
cat > "${COMPOSE_FILE}" <<COMPOSE_EOF
# Agentic Docker Stack — ${PROJECT_NAME}
# Generated by bootstrap_project.sh

services:
  orchestrator:
    image: langgraph-agent-base:latest
    container_name: ${PROJECT_NAME}_orchestrator
    volumes:
      - type: volume
        source: ${PROJECT_VOL}
        target: /app/project
        read_only: false
      - type: volume
        source: ${AGENT_VOL}
        target: /workspace
        volume:
          subpath: orchestrator
    networks:
      - agent_net
${AGENT_SERVICES}
networks:
  agent_net:
    driver: bridge
    name: ${PROJECT_NAME}_agent_net

volumes:
  ${PROJECT_VOL}:
    external: true
  ${AGENT_VOL}:
    external: true
COMPOSE_EOF

echo ""
echo "=== Done ==="
echo "  Project volume:  ${PROJECT_VOL}"
echo "  Agent volume:    ${AGENT_VOL}"
echo "  Compose file:    ${COMPOSE_FILE}"
echo "  Agents:          orchestrator + $(seq -s ', agent' 1 ${AGENT_COUNT} | sed 's/^[0-9]/agent&/')"
echo ""
echo "  Start:    docker compose -f ${COMPOSE_FILE} -p ${PROJECT_NAME} up -d"
echo "  Stop:     docker compose -f ${COMPOSE_FILE} -p ${PROJECT_NAME} down"
echo "  Teardown: docker compose -f ${COMPOSE_FILE} -p ${PROJECT_NAME} down && docker volume rm ${PROJECT_VOL} ${AGENT_VOL}"
