"""Compose file generation for the controller."""

from __future__ import annotations

from pathlib import Path
from typing import Any

import yaml

from agent_framework.schema import AgentConfig, ProjectConfig
from agent_framework.validators import apply_defaults, load_defaults


class ComposeGenerator:
    """Generates docker-compose YAML for agent stacks."""

    def __init__(self, agent_base_image: str = "langgraph-agent-base:latest") -> None:
        self._agent_base_image = agent_base_image

    def generate(
        self,
        project: ProjectConfig,
        output_path: Path,
    ) -> Path:
        """Generate a docker-compose file for the given project.

        Returns:
            Path to the generated compose file.
        """
        project_name = project.project_name
        project_vol = f"{project_name}_project_vol"
        agent_vol = f"{project_name}_agent_vol"
        flox_vol = f"{project_name}_flox_vol"
        network_name = f"{project_name}_agent_net"

        defaults = load_defaults()
        services: dict[str, Any] = {}

        for agent_key, agent in project.agents.items():
            # Apply defaults so the manifest is complete
            resolved = apply_defaults(agent, agent.type, defaults)
            is_orchestrator = agent.type == "orchestrator"

            services[agent_key] = {
                "image": self._agent_base_image,
                "container_name": f"{project_name}_{agent_key}",
                "volumes": [
                    {
                        "type": "volume",
                        "source": project_vol,
                        "target": "/app/project",
                        "read_only": not is_orchestrator,
                    },
                    {
                        "type": "volume",
                        "source": agent_vol,
                        "target": "/workspace",
                        "volume": {"subpath": agent_key},
                    },
                    {
                        "type": "volume",
                        "source": flox_vol,
                        "target": "/flox",
                        "read_only": True,
                    },
                ],
                "networks": ["agent_net"],
                "environment": {
                    "FLOX_ENV": "/flox",
                    "PATH": "/flox/.flox/run/bin:$PATH",
                    "AGENT_KEY": agent_key,
                    "PROJECT_NAME": project_name,
                },
            }

        compose = {
            "services": services,
            "networks": {
                "agent_net": {
                    "driver": "bridge",
                    "name": network_name,
                },
            },
            "volumes": {
                project_vol: {"external": True},
                agent_vol: {"external": True},
                flox_vol: {"external": True},
            },
        }

        header = (
            f"# Agentic Docker Stack — {project_name}\n"
            "# Generated by agentctl — do not edit manually\n\n"
        )
        output_path.write_text(
            header + yaml.dump(compose, default_flow_style=False, sort_keys=False)
        )
        return output_path

    def add_agent(
        self,
        compose_path: Path,
        agent_key: str,
        agent: AgentConfig,
        project_name: str,
    ) -> None:
        """Add a single agent service to an existing compose file.

        Reads the existing compose, appends the service, and rewrites.
        """
        data = yaml.safe_load(compose_path.read_text())
        if data is None:
            data = {}
        services = data.setdefault("services", {})

        defaults = load_defaults()
        resolved = apply_defaults(agent, agent.type, defaults)
        is_orchestrator = agent.type == "orchestrator"

        project_vol = f"{project_name}_project_vol"
        agent_vol = f"{project_name}_agent_vol"
        flox_vol = f"{project_name}_flox_vol"

        services[agent_key] = {
            "image": self._agent_base_image,
            "container_name": f"{project_name}_{agent_key}",
            "volumes": [
                {
                    "type": "volume",
                    "source": project_vol,
                    "target": "/app/project",
                    "read_only": not is_orchestrator,
                },
                {
                    "type": "volume",
                    "source": agent_vol,
                    "target": "/workspace",
                    "volume": {"subpath": agent_key},
                },
                {
                    "type": "volume",
                    "source": flox_vol,
                    "target": "/flox",
                    "read_only": True,
                },
            ],
            "networks": ["agent_net"],
            "environment": {
                "FLOX_ENV": "/flox",
                "PATH": "/flox/.flox/run/bin:$PATH",
                "AGENT_KEY": agent_key,
                "PROJECT_NAME": project_name,
            },
        }

        header = (
            f"# Agentic Docker Stack — {project_name}\n"
            "# Generated by agentctl — do not edit manually\n\n"
        )
        compose_path.write_text(
            header + yaml.dump(data, default_flow_style=False, sort_keys=False)
        )

    def remove_agent(self, compose_path: Path, agent_key: str) -> None:
        """Remove a service from an existing compose file."""
        data = yaml.safe_load(compose_path.read_text())
        if data is None:
            return
        services = data.get("services", {})
        if agent_key in services:
            del services[agent_key]
            # Try to infer project name from first remaining service's container_name
            project_name = "unknown"
            for svc in services.values():
                cname = svc.get("container_name", "")
                if "_" in cname:
                    project_name = cname.rsplit("_", 1)[0]
                    break
            header = (
                f"# Agentic Docker Stack — {project_name}\n"
                "# Generated by agentctl — do not edit manually\n\n"
            )
            compose_path.write_text(
                header + yaml.dump(data, default_flow_style=False, sort_keys=False)
            )
